name: 'enterprise_dbt'
version: '1.0.0'
config-version: 2

# Mengarahkan dbt untuk mencari profil bernama 'enterprise_dbt' di profiles.yml
profile: 'enterprise_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Konfigurasi Model berdasarkan Layering Target Arsitektur
models:
  enterprise_dbt:
    # 1. Staging Layer: Hanya membersihkan dan memformat data mentah (raw)
    staging:
      +materialized: view
      +schema: staging
    
    # 2. Intermediate Layer: Transformasi/Join kompleks sebelum jadi Marts
    intermediate:
      +materialized: ephemeral # Menghemat storage di Postgres, jadi subquery
      +schema: intermediate

    # 3. Marts Layer: Siap dikonsumsi oleh BI / Superset
    marts:
      +materialized: table
      +schema: marts